spring.application.name=gateway
eureka.client.enabled=true 
eureka.client.register-with-eureka=true
spring.profiles.active=${PROFILE}
thirdeye.resume.updater.api.key=${THIRDEYE_RESUME_UPDATER_API_KEY}
aiintegreater.api.key=${THIRDEYE_AI_INTEGREATER_API_KEY}
interviewperpadmin.api.key=${THIRDEYE_INTERVIEWPERP_ADMIN_API_KEY}
eureka.instance.instance-id=${spring.application.name}:${server.port}
eureka.instance.prefer-ip-address=true
thirdeye.timezone = Asia/Kolkata
spring.main.web-application-type=reactive
thirdeye.resumeupdater.frontend.urls=${THIRDEYE_RESUME_UPDATER_FRONTEND_URLS}

spring.cloud.gateway.routes[0].id=THIRDEYE30-RESUMEHELPER-TOKENMANAGER
spring.cloud.gateway.routes[0].uri=lb://TOKENMANAGER
spring.cloud.gateway.routes[0].predicates[0]=Path=/tokenmanager/**
spring.cloud.gateway.routes[0].filters[0].name=Retry
spring.cloud.gateway.routes[0].filters[0].args.retries=3
spring.cloud.gateway.routes[0].filters[0].args.series=SERVER_ERROR
spring.cloud.gateway.routes[0].filters[0].args.statuses=BAD_GATEWAY,GATEWAY_TIMEOUT
spring.cloud.gateway.routes[0].filters[0].args.methods=GET
spring.cloud.gateway.routes[0].filters[0].args.exceptions=java.io.IOException,java.util.concurrent.TimeoutException
spring.cloud.gateway.routes[0].filters[0].args.backoff.firstBackoff=10ms
spring.cloud.gateway.routes[0].filters[0].args.backoff.maxBackoff=100ms
spring.cloud.gateway.routes[0].filters[0].args.backoff.factor=2
spring.cloud.gateway.routes[0].filters[0].args.backoff.basedOnPreviousValue=false

spring.cloud.gateway.routes[1].id=THIRDEYE30-RESUMEHELPER-RESUMEMANAGER
spring.cloud.gateway.routes[1].uri=lb://RESUMEMANAGER
spring.cloud.gateway.routes[1].predicates[0]=Path=/resumemanager/**
spring.cloud.gateway.routes[1].filters[0].name=Retry
spring.cloud.gateway.routes[1].filters[0].args.retries=3
spring.cloud.gateway.routes[1].filters[0].args.series=SERVER_ERROR
spring.cloud.gateway.routes[1].filters[0].args.statuses=BAD_GATEWAY,GATEWAY_TIMEOUT
spring.cloud.gateway.routes[1].filters[0].args.methods=GET
spring.cloud.gateway.routes[1].filters[0].args.exceptions=java.io.IOException,java.util.concurrent.TimeoutException
spring.cloud.gateway.routes[1].filters[0].args.backoff.firstBackoff=10ms
spring.cloud.gateway.routes[1].filters[0].args.backoff.maxBackoff=100ms
spring.cloud.gateway.routes[1].filters[0].args.backoff.factor=2
spring.cloud.gateway.routes[1].filters[0].args.backoff.basedOnPreviousValue=false

spring.cloud.gateway.routes[2].id=THIRDEYE30-RESUMEHELPER-MESSAGEBROKER-AIINTEGREATER
spring.cloud.gateway.routes[2].uri=lb://MESSAGEBROKER
spring.cloud.gateway.routes[2].predicates[0]=Path=/messagebroker/message/aiintegreater/**,/messagebroker/message/aiintegreater2/**
spring.cloud.gateway.routes[2].filters[0]=AiIntegreaterFilter
spring.cloud.gateway.routes[2].filters[1].name=Retry
spring.cloud.gateway.routes[2].filters[1].args.retries=3
spring.cloud.gateway.routes[2].filters[1].args.series=SERVER_ERROR
spring.cloud.gateway.routes[2].filters[1].args.statuses=BAD_GATEWAY,GATEWAY_TIMEOUT
spring.cloud.gateway.routes[2].filters[1].args.methods=GET
spring.cloud.gateway.routes[2].filters[1].args.exceptions=java.io.IOException,java.util.concurrent.TimeoutException
spring.cloud.gateway.routes[2].filters[1].args.backoff.firstBackoff=10ms
spring.cloud.gateway.routes[2].filters[1].args.backoff.maxBackoff=100ms
spring.cloud.gateway.routes[2].filters[1].args.backoff.factor=2
spring.cloud.gateway.routes[2].filters[1].args.backoff.basedOnPreviousValue=false

spring.cloud.gateway.routes[3].id=THIRDEYE30-RESUMEHELPER-PDFGENERATER
spring.cloud.gateway.routes[3].uri=lb://PDFGENERATER
spring.cloud.gateway.routes[3].predicates[0]=Path=/pdfgenerater/**
spring.cloud.gateway.routes[3].filters[0].name=Retry
spring.cloud.gateway.routes[3].filters[0].args.retries=3
spring.cloud.gateway.routes[3].filters[0].args.series=SERVER_ERROR
spring.cloud.gateway.routes[3].filters[0].args.statuses=BAD_GATEWAY,GATEWAY_TIMEOUT
spring.cloud.gateway.routes[3].filters[0].args.methods=GET
spring.cloud.gateway.routes[3].filters[0].args.exceptions=java.io.IOException,java.util.concurrent.TimeoutException
spring.cloud.gateway.routes[3].filters[0].args.backoff.firstBackoff=10ms
spring.cloud.gateway.routes[3].filters[0].args.backoff.maxBackoff=100ms
spring.cloud.gateway.routes[3].filters[0].args.backoff.factor=2
spring.cloud.gateway.routes[3].filters[0].args.backoff.basedOnPreviousValue=false

spring.cloud.gateway.routes[4].id=THIRDEYE30-RESUMEHELPER-INTERVIEWPREP-ADMIN
spring.cloud.gateway.routes[4].uri=lb://INTERVIEWPREP
spring.cloud.gateway.routes[4].predicates[0]=Path=/interviewperp/admin/**
spring.cloud.gateway.routes[4].filters[0]=InterviewperpAdminFilter
spring.cloud.gateway.routes[4].filters[1].name=Retry
spring.cloud.gateway.routes[4].filters[1].args.retries=3
spring.cloud.gateway.routes[4].filters[1].args.series=SERVER_ERROR
spring.cloud.gateway.routes[4].filters[1].args.statuses=BAD_GATEWAY,GATEWAY_TIMEOUT
spring.cloud.gateway.routes[4].filters[1].args.methods=GET
spring.cloud.gateway.routes[4].filters[1].args.exceptions=java.io.IOException,java.util.concurrent.TimeoutException
spring.cloud.gateway.routes[4].filters[1].args.backoff.firstBackoff=10ms
spring.cloud.gateway.routes[4].filters[1].args.backoff.maxBackoff=100ms
spring.cloud.gateway.routes[4].filters[1].args.backoff.factor=2
spring.cloud.gateway.routes[4].filters[1].args.backoff.basedOnPreviousValue=false

spring.cloud.gateway.routes[5].id=THIRDEYE30-RESUMEHELPER-INTERVIEWPREP
spring.cloud.gateway.routes[5].uri=lb://INTERVIEWPREP
spring.cloud.gateway.routes[5].predicates[0]=Path=/interviewperp/**
spring.cloud.gateway.routes[5].filters[0].name=Retry
spring.cloud.gateway.routes[5].filters[0].args.retries=3
spring.cloud.gateway.routes[5].filters[0].args.series=SERVER_ERROR
spring.cloud.gateway.routes[5].filters[0].args.statuses=BAD_GATEWAY,GATEWAY_TIMEOUT
spring.cloud.gateway.routes[5].filters[0].args.methods=GET
spring.cloud.gateway.routes[5].filters[0].args.exceptions=java.io.IOException,java.util.concurrent.TimeoutException
spring.cloud.gateway.routes[5].filters[0].args.backoff.firstBackoff=10ms
spring.cloud.gateway.routes[5].filters[0].args.backoff.maxBackoff=100ms
spring.cloud.gateway.routes[5].filters[0].args.backoff.factor=2
spring.cloud.gateway.routes[5].filters[0].args.backoff.basedOnPreviousValue=false

